# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: dfde5b0e52f864d155d9c354ddf2b34907ccafa13fe08155dedf3d680c3334fdddc95eca18be7b40f038b1a922289d845d6a600476fb8c700d900fb0ccb00dd1

test:
  secret_key_base: 8de033f259672a143708e4647eebaa91ffa118c765f80a3251aef30c908800ccfdd9139a8e7e25af35a2a8150c2d4445fb61a27f8e3d85015a8c08503dce7514

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
